### ISSUE TITLE
Cannot perform list, start, end

### ISSUE THREAD

**Issue by chunkdaddy** [NickLewry/pd-snooze#5] opened 2018-07-30 14:52 UTC
I was very excited to find this utility, but that excitement quickly drained, as I can install pd-snooze v2.1.0, I can set the config, and I can show the current config.  But every single other command gives the following error.  I have tried with both node v9.9.0 and v8.11.3, under both MacOS and Windows:
Error retrieving services: TypeError: Cannot read property 'map' of undefined.

C:\temp>pd-snooze list -s
Error retrieving services: TypeError: Cannot read property 'map' of undefined
(node:4464) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Services.listServices (C:\Users\scott.stewart\AppData\Roaming\npm\node_modules\pd-snooze\src\services\services.js:45:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\temp>node -v
v8.11.3

C:\temp>pd-snooze -v
2.1.0

C:\temp>pd-snooze current-config
{
  "email": "scott.stewart@blackbook.com",
  "apiKey": "XXXXXXXXXXX",
  "timeZone": "America/New York"
}
C:\temp>pd-snooze list --services
Error retrieving services: TypeError: Cannot read property 'map' of undefined
(node:9948) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Services.listServices (C:\Users\scott.stewart\AppData\Roaming\npm\node_modules\pd-snooze\src\services\services.js:45:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

MacOS:
LOSX-346127-HBM-N:~ jstewart$ pd-snooze list -s
Error retrieving services: TypeError: Cannot read property 'map' of undefined
(node:44897) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Services.listServices (/usr/local/lib/node_modules/pd-snooze/src/services/services.js:45:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:44897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
LOSX-346127-HBM-N:~ jstewart$ node -v
v9.9.0
LOSX-346127-HBM-N:~ jstewart$ pd-snooze -v
2.1.0
LOSX-346127-HBM-N:~ jstewart$ pd-snooze start -a
Error retrieving services: TypeError: Cannot read property 'map' of undefined
LOSX-346127-HBM-N:~ jstewart$ pd-snooze start --all
Error retrieving services: TypeError: Cannot read property 'map' of undefined

Any help is greatly appreciated!

**Comment by NickLewry** [comment] 2018-07-30 15:04
@chunkdaddy thank you for reporting this, I will investigate it this week and get back to you with any questions or resolve it!

**Comment by chunkdaddy** [comment] 2018-08-10 03:40
Nick - any update? The one thing in common I failed to mention before was on all of my attempts node was a fresh install, as in it had not existed on the target server before. The process was literally install node, install pd-snooze via npm, set the config, verify config, attempt to snooze. 

We have options in terms of what OS platform we can run on, and I certainly don’t mind downgrading to an earlier version of pd-snooze and/or nodejs while things get resolved. 

If you can comment on some known-good combinations of pd-snooze and node that I haven’t tried

**Comment by chunkdaddy** [comment] 2018-08-10 03:42
Hit the wrong button! Whoops. Reopened, sorry about that!

**Comment by NickLewry** [comment] 2018-08-10 16:01
Hi @chunkdaddy, thank you for your patience! I have found the cause of your issue which wasn't made obvious due to a poor Readme and error handling. The issue is that your timezone config key is in the incorrect format "America/ New York" when it should be "America/New_York". I have added a timezone key to the Readme which shows the correct formats for timezones and prompted the user to double check their config if they come across a similar issue. I have also just updated the tool so please download the latest version 2.2.1.

I am going to close this as I was able to reproduce it and fix it with the correct timezone format.

**Closed by NickLewry** 2018-08-10 16:01 UTC

**Comment by chunkdaddy** [comment] 2018-08-14 00:19
@NickLewry - By the way, do you know of anyone running this as any of the following:  AWS Lambda Function, AWS Beanstalk App, AWS SSM task, Serverless app, or tied in to a slackbot like Hubot?  i'm trying to figure out a way to "host" this but not where it's installed on every server that has to run it.  Thanks!

**Comment by NickLewry** [comment] 2018-08-15 10:36
Very happy to hear it worked so well and you will be recommending it thank you! Unfortunately with regards to your second comment I don't know of anyone using it like that, if you do find a way to do it I would be interested to hear how you got on.

Thanks
